list_of_exercises = [
    { 'name': 'Distance Running',
      'exercise_type': 'ExerciseRunning' },
    { 'name': 'Push Ups',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Leg Press',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Hack Squat',
      'exercise_type': 'ExerciseSetsRepsWeights' }, 
    { 'name': 'Calf Raise',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Deadlift',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Romanian Deadlift',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Barbell Squat',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Lying Leg Curl',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Leg Extension',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Pull Ups',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Lying T-Bar Row',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'T-Bar Row',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Leverage Iso Row',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Lat Pulldown',
      'exercise_type': 'ExerciseSetsRepsWeights' },    
    { 'name': 'Machine Bench Press',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Barbell Bench Press',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Leverage Shoulder Press',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Standing Military Press',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Upright Barbell Row',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Triceps Pushdown',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Dips',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Machine Biceps Curl',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Barbell Curl',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Hammer Curl',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Hyperextenstion',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Decline Crunch',
      'exercise_type': 'ExerciseSetsRepsWeights' },
    { 'name': 'Hanging Leg Raise',
      'exercise_type': 'ExerciseSetsRepsWeights' }
]
